// Code generated by "stringer -type=Code -trimprefix=Code"; DO NOT EDIT.

package resp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeSuccess-200]
	_ = x[CodeBaseErr-500]
	_ = x[CodeParamErr-501]
	_ = x[CodeNotLogin-502]
}

const (
	_Code_name_0 = "Success"
	_Code_name_1 = "BaseErrParamErrNotLogin"
)

var (
	_Code_index_1 = [...]uint8{0, 7, 15, 23}
)

func (i Code) String() string {
	switch {
	case i == 200:
		return _Code_name_0
	case 500 <= i && i <= 502:
		i -= 500
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
